# package dependencies
# (sorted ascendingly by project name)

[[constraint]]
  name = "github.com/grantae/certinfo"
  revision = "59d56a35515b3ab2326749924739cfe58facc991" # 2017/04/12 (master)

[[constraint]]
  name = "github.com/otiai10/copy"
  version = "=v1.0.2"

[[constraint]]
  name = "github.com/integrii/flaggy"
  version = "=1.4.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "=v1.4.7"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=1.4.2"

[[constraint]]
  name = "github.com/tredoe/osutil"
  revision = "e272fdda81c81c765770354538073f24a0d460f5" # 2019/10/18 (master)

[[constraint]]
  name = "github.com/alecthomas/participle"
  version = "=0.3.0"

[[constraint]]
  name = "github.com/mozilla-services/pkcs7"
  revision = "432b2356ecb18209c1cec25680b8a23632794f21"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "86b910548bc16777f40503131aa424ae0a092199" # 2019/01/13 (master)

[[constraint]]
  name = "github.com/spf13/viper"
  version = "=v1.6.2"

[prune]
  go-tests = true
  unused-packages = true
