[[constraint]]
  name = "github.com/integrii/flaggy"
  version = "=1.4.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=1.4.2"

[[constraint]]
  name = "github.com/alecthomas/participle"
  version = "=0.3.0"

[prune]
  go-tests = true
  unused-packages = true
